In [1]:
from datetime import datetime
import os
import glob
from os.path import join


In [2]:
now = datetime.now()


experiment_checkpoints_path = join('tmp','pipeline_logs','solver','*v0_35c83_00000_0_2023*','checkpoint_*')


In [3]:
from rllib_utills.policies_wrapper import RLLibPolicy
from envs import env_creator
from base_rl.evaluation import Evaluator

checkpoints = glob.glob(experiment_checkpoints_path)
checkpoint_path = max(checkpoints, key=os.path.getctime)
print(checkpoint_path)
policy_kwargs = dict(checkpoint_path=checkpoint_path)
evaluator = Evaluator(env_creator=env_creator, env_kwargs={}, policy_class=RLLibPolicy,policy_kwargs=policy_kwargs)
evaluator.evaluate(epochs=1,render=True, sample_action=True)

/home/hamza/PycharmProjects/example-medicine-delievery-system/venv/lib/python3.10/site-packages/tensorflow_probability/python/__init__.py:57: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if (distutils.version.LooseVersion(tf.__version__) <


tmp/pipeline_logs/solver/PPO_dosing-v0_35c83_00000_0_2023-06-15_18-25-15/checkpoint_000550


/home/hamza/PycharmProjects/example-medicine-delievery-system/venv/lib/python3.10/site-packages/gym/spaces/box.py:84: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
/home/hamza/PycharmProjects/example-medicine-delievery-system/venv/lib/python3.10/site-packages/ray/rllib/utils/filter.py:84: DeprecationWarning: Passing None into shape arguments as an alias for () is deprecated.
  self.mean_array = np.zeros(shape)


Action: 0.0
[6.999964e+01 1.199700e+02 3.699000e+01 1.800000e-02]
[ True  True  True  True]
[False False False False]
1
0.75
Current Heart Rate: 69.99964
Current Blood Pressure: 119.97
Current Temperature: 36.99
Current Dosage: 0.018000000000000002
Action: 0.0
[6.99993929e+01 1.19966046e+02 3.69867600e+01 1.96400000e-02]
[ True  True  True  True]
[False False False False]
2
0.75
Current Heart Rate: 69.99939288952
Current Blood Pressure: 119.966046
Current Temperature: 36.986760000000004
Current Dosage: 0.01964
Action: 0.0
[6.99991167e+01 1.19961761e+02 3.69831777e+01 1.96072000e-02]
[ True  True  True  True]
[False False False False]
3
0.75
Current Heart Rate: 69.99911674476459
Current Blood Pressure: 119.961760633428
Current Temperature: 36.98317774
Current Dosage: 0.0196072
Action: 0.0
[6.99988158e+01 1.19957658e+02 3.69794060e+01 1.96078560e-02]
[ True  True  True  True]
[False False False False]
4
0.75
Current Heart Rate: 69.99881578207285
Current Blood Pressure: 119.95765795347128